"""add_study_rollcall_teacher_tables

Revision ID: 7a15771bdc7b
Revises: 
Create Date: 2026-05-01 20:18:53.523617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a15771bdc7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor_type IN ('student','teacher','system')", name='ck_audit_actor_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_type', 'actor_id', 'created_at'], unique=False)
    op.create_index('idx_audit_target', 'audit_logs', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('target_email', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('email','push','in_app')", name='ck_notif_channel'),
    sa.CheckConstraint("status IN ('pending','sent','failed','retrying')", name='ck_notif_status'),
    sa.CheckConstraint("target_type IN ('student','teacher','role')", name='ck_notif_target_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_status', 'notification_log', ['status', 'created_at'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grade_code', sa.String(length=2), nullable=False),
    sa.Column('class_code', sa.String(length=2), nullable=False),
    sa.Column('seat_no', sa.String(length=2), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_kana', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('room_no', sa.String(length=8), nullable=False),
    sa.Column('dorm_unit', sa.SmallInteger(), nullable=False),
    sa.Column('is_overseas', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("(gender = 'male' AND dorm_unit IN (1, 2)) OR (gender = 'female' AND dorm_unit = 4)", name='ck_students_gender_dorm'),
    sa.CheckConstraint("status IN ('active', 'locked', 'graduated', 'transferred', 'paused')", name='ck_students_status'),
    sa.CheckConstraint('dorm_unit IN (1, 2, 4)', name='ck_students_dorm_unit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_code', 'class_code', 'seat_no', name='uq_students_no')
    )
    op.create_index('idx_students_dorm', 'students', ['dorm_unit', 'status'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('assigned_dorm', sa.SmallInteger(), nullable=True),
    sa.Column('failed_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('寮務部長','寮務課長','国際交流部長','国際交流課長','管理係','寮監','学習担当','寮務一般教師')", name='ck_teachers_role'),
    sa.CheckConstraint("status IN ('active','disabled')", name='ck_teachers_status'),
    sa.CheckConstraint('assigned_dorm IS NULL OR assigned_dorm IN (1, 2, 4)', name='ck_teachers_dorm'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('failed_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_level', sa.SmallInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('leave_method', sa.Text(), nullable=False),
    sa.Column('leave_time', sa.Time(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('return_method', sa.Text(), nullable=False),
    sa.Column('return_time', sa.Time(), nullable=False),
    sa.Column('stay_locations', sa.JSON(), nullable=True),
    sa.Column('meals_skip_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meals_skip_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_dep_air', sa.Text(), nullable=True),
    sa.Column('flight_dep_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_arr_air', sa.Text(), nullable=True),
    sa.Column('flight_arr_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bus_route_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('帰省','外泊','帰国')", name='ck_app_kind'),
    sa.CheckConstraint("status IN ('pending','approved_partial','approved','rejected','withdrawn')", name='ck_app_status'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_status_date', 'applications', ['status', 'leave_date'], unique=False)
    op.create_index('idx_app_student', 'applications', ['student_id', 'status'], unique=False)
    op.create_table('class_teacher_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('grade_code', sa.String(length=2), nullable=False),
    sa.Column('class_code', sa.String(length=2), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('is_homeroom', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_code', 'class_code', 'academic_year', 'is_homeroom', 'effective_from', name='uq_cta_assignment')
    )
    op.create_index('idx_cta_class', 'class_teacher_assignment', ['grade_code', 'class_code', 'academic_year'], unique=False)
    op.create_index('idx_cta_teacher', 'class_teacher_assignment', ['teacher_id'], unique=False)
    op.create_table('rollcall_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dorm_unit_set', sa.JSON(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('schedule_mode', sa.String(length=16), nullable=False),
    sa.Column('day_type', sa.String(length=16), nullable=False),
    sa.Column('session_status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_source', sa.String(length=16), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_source', sa.String(length=16), nullable=True),
    sa.Column('ended_by', sa.Uuid(), nullable=True),
    sa.Column('scheduled_window_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_on_time_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_late_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_auto_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settle_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("day_type IN ('weekday','weekend_holiday')", name='ck_rcs_day_type'),
    sa.CheckConstraint("schedule_mode IN ('split','merged_normal')", name='ck_rcs_mode'),
    sa.CheckConstraint("session_status IN ('draft','running','ended')", name='ck_rcs_status'),
    sa.CheckConstraint("session_type IN ('morning','evening')", name='ck_rcs_type'),
    sa.ForeignKeyConstraint(['ended_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_absence_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_sar_status'),
    sa.ForeignKeyConstraint(['decided_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'target_date', name='uq_sar_date')
    )
    op.create_index('idx_sar_date_status', 'study_absence_requests', ['target_date', 'status'], unique=False)
    op.create_table('study_checkins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('overridden_by', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('init','present','late','absent','exempt')", name='ck_sc_status'),
    sa.ForeignKeyConstraint(['overridden_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'target_date', name='uq_sc_date')
    )
    op.create_index('idx_sc_date_status', 'study_checkins', ['target_date', 'status'], unique=False)
    op.create_table('study_roster',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_term', sa.String(length=16), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_term', name='uq_roster_term')
    )
    op.create_index('idx_roster_term', 'study_roster', ['academic_term', 'removed_at'], unique=False)
    op.create_table('teacher_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('target_email', sa.Text(), nullable=False),
    sa.Column('target_role', sa.String(length=32), nullable=False),
    sa.Column('target_dorm', sa.SmallInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_tinv_token', 'teacher_invitations', ['token'], unique=False)
    op.create_table('application_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('approver_role', sa.String(length=16), nullable=False),
    sa.Column('chain_order', sa.SmallInteger(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=8), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("approver_role IN ('担任','寮務部長','寮務課長','国際交流部長','国際交流課長','管理係')", name='ck_approval_role'),
    sa.CheckConstraint("decision IS NULL OR decision IN ('approve','reject')", name='ck_approval_decision'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'approver_role', name='uq_approval_role')
    )
    op.create_table('rollcall_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('path_type', sa.String(length=8), nullable=True),
    sa.Column('base_status', sa.String(length=24), nullable=False),
    sa.Column('status_source', sa.String(length=24), nullable=False),
    sa.Column('applied_group', sa.String(length=16), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('card_uid', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("base_status IN ('init','present','late','absent','exempt_range')", name='ck_rce_status'),
    sa.CheckConstraint("status_source IN ('auto_nfc','auto_settle','manual_checkin','teacher_override')", name='ck_rce_source'),
    sa.ForeignKeyConstraint(['session_id'], ['rollcall_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rce_session_student', 'rollcall_events', ['session_id', 'student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rce_session_student', table_name='rollcall_events')
    op.drop_table('rollcall_events')
    op.drop_table('application_approvals')
    op.drop_index('idx_tinv_token', table_name='teacher_invitations')
    op.drop_table('teacher_invitations')
    op.drop_index('idx_roster_term', table_name='study_roster')
    op.drop_table('study_roster')
    op.drop_index('idx_sc_date_status', table_name='study_checkins')
    op.drop_table('study_checkins')
    op.drop_index('idx_sar_date_status', table_name='study_absence_requests')
    op.drop_table('study_absence_requests')
    op.drop_table('rollcall_sessions')
    op.drop_index('idx_cta_teacher', table_name='class_teacher_assignment')
    op.drop_index('idx_cta_class', table_name='class_teacher_assignment')
    op.drop_table('class_teacher_assignment')
    op.drop_index('idx_app_student', table_name='applications')
    op.drop_index('idx_app_status_date', table_name='applications')
    op.drop_table('applications')
    op.drop_table('accounts')
    op.drop_table('teachers')
    op.drop_index('idx_students_dorm', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_notif_status', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index('idx_audit_target', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
